# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('business_name', models.CharField(max_length=30)),
                ('business_desc', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'business',
                'verbose_name_plural': 'business',
            },
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('uid', models.IntegerField(default=-1, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50, unique=True)),
                ('password', models.CharField(default='', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('geolat', models.CharField(blank=True, max_length=10)),
                ('geolong', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('dob', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Consumer',
                'verbose_name_plural': 'Consumers',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('uid', models.IntegerField(default=-1, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50, unique=True)),
                ('password', models.CharField(default='', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('geolat', models.CharField(blank=True, max_length=10)),
                ('geolong', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'vendor',
                'verbose_name_plural': 'vendors',
            },
        ),
    ]
